sequenceDiagram
    participant App as Aplicação (Ex: Datasource)
    participant Helper as DatabaseHelper (instance)
    participant SQLite as sqflite / SO

    App->>Helper: Acessa getter .database
    alt _database já existe em cache
        Helper-->>App: Retorna instância de conexão ativa
    else _database é nulo (primeira chamada)
        Helper->>Helper: Invoca _initDB('pet_care.db')
        Helper->>SQLite: getDatabasesPath() (obtem diretório padrão)
        SQLite-->>Helper: Retorna caminho físico do diretório
        Helper->>Helper: Determina caminho final usando path.join()
        Helper->>SQLite: openDatabase()
        alt É a primeira vez abrindo o banco (arquivo não existe)
            SQLite->>Helper: Dispara callback onCreate (_createDB)
            Helper->>SQLite: Executa SQL DDL (CREATE TABLE pets)
        end
        SQLite-->>Helper: Retorna instância do Banco físico conectado
        Helper->>Helper: Salva instância no cache estático (_database)
        Helper-->>App: Retorna conexão pronta para uso
    end
